fixed typos

diff --git a/install b/install
--- a/install
+++ b/install
@@ -52,6 +52,20 @@ logo "Press any key to continue..."
 read
 
 # Information gathering
+prompt "Hostname" HOSTNAME macbook
+prompt "Root password" MASTER_PASSWORD "None"
+prompt "Username" USERNAME "None"
+prompt "Password" PASSWORD "None"
+prompt "Timezone" TIMEZONE "Africa/Algiers"
+
+select AUDIO_SERVER in "Pipewire (New, suitable for modern multimedia needs)" "Pulseaudio (Old, suitable for traditional Linux audio needs)"; do
+    case $AUDIO_SERVER in
+        "") AUDIO_SERVER="pipewire"; break;;
+        "Pipewire (New, suitable for modern multimedia needs)") AUDIO_SERVER="pipewire"; break;;
+        "Pulseaudio (Old, suitable for traditional Linux audio needs)") AUDIO_SERVER="pulseaudio"; break;;
+    esac
+done
+
 devices=$(lsblk -o NAME,SIZE | grep -e '^sd\|^nvme')
 PS3="Select a disk: "
 echo "Available devices:"
@@ -67,20 +81,6 @@ select device in "${options[@]}"; do
         "") echo "Invalid selection";;
         "Quit") exit;;
         *) DISK=$(echo $device | awk '{print $1}'); break;;
-    esac
-done
-
-prompt "Hostname" HOSTNAME macbook
-prompt "Root password" MASTER_PASSWORD "None"
-prompt "Username" USERNAME "None"
-prompt "Password" PASSWORD "None"
-prompt "Timezone" TIMEZONE "Africa/Algiers"
-
-select AUDIO_SERVER in "Pipewire (New, suitable for modern multimedia needs)" "Pulseaudio (Old, suitable for traditional Linux audio needs)"; do
-    case $AUDIO_SERVER in
-        "") AUDIO_SERVER="pipewire"; break;;
-        "Pipewire (New, suitable for modern multimedia needs)") AUDIO_SERVER="pipewire"; break;;
-        "Pulseaudio (Old, suitable for traditional Linux audio needs)") AUDIO_SERVER="pulseaudio"; break;;
     esac
 done
 
@@ -122,6 +122,100 @@ cp -fvr /etc/pacman.d/mirrorlist /mnt/etc/pacman.d/mirrorlist
 cp -fvr /root/archy/postinstall /root/archy/packages /root/archy/.env /mnt
 ( arch-chroot /mnt /postinstall ) |& tee postinstall.log
 cp -fvr postinstall.log /mnt
+
+
+
+
+echo -ne "
+------------------------------------------------------------------------------------------
+                                Setup Language And Locale
+------------------------------------------------------------------------------------------
+"
+sed -i 's/^#en_US.UTF-8 UTF-8/en_US.UTF-8 UTF-8/' /etc/locale.gen
+locale-gen
+ln -s /usr/share/zoneinfo/${TIMEZONE} /etc/localtime
+hwclock --systohc
+sed -i 's/^#ParallelDownloads/ParallelDownloads/' /etc/pacman.conf
+
+echo -ne "
+------------------------------------------------------------------------------------------
+                                     Adding User
+------------------------------------------------------------------------------------------
+"
+groupadd libvirt
+useradd -m -G wheel,audio,video,libvirt -s /bin/bash --badname ${USERNAME}
+ENCRYPTED_MASTER_PASSWORD=$(openssl passwd -6 -salt 'salt' ${MASTER_PASSWORD})
+ENCRYPTED_PASSWORD=$(openssl passwd -6 -salt 'salt' ${PASSWORD})
+usermod --password "${ENCRYPTED_MASTER_PASSWORD}" root
+usermod --password "${ENCRYPTED_PASSWORD}" ${USERNAME}
+echo "${HOSTNAME}" > /etc/hostname
+
+echo -ne "
+------------------------------------------------------------------------------------------
+                                 Creating GRUB Boot Menu
+------------------------------------------------------------------------------------------
+"
+pacman -S --noconfirm --needed grub os-prober efibootmgr dhcpcd
+grub-install --target=x86_64-efi --efi-directory=/boot/efi --bootloader-id=grub
+sed -i 's/GRUB_CMDLINE_LINUX_DEFAULT="[^"]*/& rootflags=data=writeback libata.force=1:noncq acpi_osi=!Darwin/' /etc/default/grub
+sed -i 's/^GRUB_TIMEOUT=5/GRUB_TIMEOUT=0/' /etc/default/grub
+sed -i 's/^#GRUB_DISABLE_SUBMENU=y/GRUB_DISABLE_SUBMENU=y/' /etc/default/grub
+grub-mkconfig -o /boot/grub/grub.cfg
+
+echo -ne "
+------------------------------------------------------------------------------------------
+                                  Installing packages
+------------------------------------------------------------------------------------------
+"
+if [[ ! -f "packages" ]]; then
+  echo "Error: packages file not found."
+  exit 1
+fi
+while read line
+do
+  if [[ $line == "" ]] || [[ $line == \#* ]]; then
+    continue
+  fi
+  pacman -Sy --noconfirm --needed "$line"
+done < packages
+
+echo -ne "
+------------------------------------------------------------------------------------------
+                                     Switch shell
+------------------------------------------------------------------------------------------
+"
+chsh -s ${SHELL} root
+chsh -s ${SHELL} ${USERNAME}
+
+echo -ne "
+------------------------------------------------------------------------------------------
+                               Managing Essential Services
+------------------------------------------------------------------------------------------
+"
+systemctl disable --now transmission.service
+systemctl enable  --now dhcpcd.service
+systemctl enable  --now NetworkManager.service
+
+echo -ne "
+------------------------------------------------------------------------------------------
+                              Changing Default Console Font
+------------------------------------------------------------------------------------------
+"
+echo -ne 'KEYMAP="us"
+FONT="ter-132b"
+' > /etc/vconsole.conf
+
+echo -ne "
+------------------------------------------------------------------------------------------
+                                Add no password sudo rights
+------------------------------------------------------------------------------------------
+"
+sed -ni "/^root/{a\
+  ${USERNAME} ALL=(ALL:ALL) NOPASSWD: ALL
+p}" /etc/sudoers
+
+
+
 
 logo "Done - Please Eject Install Media"
 # umount -R /mnt
