fixed postinstall script

diff --git a/postinstall b/postinstall
--- a/postinstall
+++ b/postinstall
@@ -59,7 +59,7 @@ echo -ne "
                                  Creating GRUB Boot Menu
 ------------------------------------------------------------------------------------------
 "
-pacman -S --noconfirm --needed grub os-prober efibootmgr
+pacman -S --noconfirm --needed grub os-prober efibootmgr dhcpcd
 grub-install --target=x86_64-efi --efi-directory=/boot/efi --bootloader-id=grub
 # sed -i 's/GRUB_CMDLINE_LINUX_DEFAULT="[^"]*/& rootflags=data=writeback libata.force=1:noncq acpi_osi=!Darwin/' /etc/default/grub
 # sed -i 's/^GRUB_TIMEOUT=5/GRUB_TIMEOUT=0/' /etc/default/grub
@@ -71,17 +71,17 @@ echo -ne "
                                   Installing packages
 ------------------------------------------------------------------------------------------
 "
-if [[ ! -f "packages" ]]; then
-  echo "Error: packages file not found."
-  exit 1
-fi
-while read line
-do
-  if [[ $line == "" ]] || [[ $line == \#* ]]; then
-    continue
-  fi
-  pacman -Sy --noconfirm --needed "$line"
-done < packages
+# if [[ ! -f "packages" ]]; then
+#   echo "Error: packages file not found."
+#   exit 1
+# fi
+# while read line
+# do
+#   if [[ $line == "" ]] || [[ $line == \#* ]]; then
+#     continue
+#   fi
+#   pacman -Sy --noconfirm --needed "$line"
+# done < packages
 
 echo -ne "
 ------------------------------------------------------------------------------------------
